In [1]:
import pandas as pd

In [39]:
census = pd.read_csv('ACS_13_5YR_DP03_with_ann.csv', usecols=['GEO.id2', 'HC03_VC171'])
census = census.loc[1:,:]
census.columns = ['zip','povertyRate']
census.to_csv('censusCleaned.csv', index = False)

         zip povertyRate
1      00601        59.1
2      00602        54.3
3      00603        50.1
4      00606        56.5
5      00610        50.5
6      00612        45.3
7      00616        47.3
8      00617        53.8
9      00622        60.3
10     00623        47.8
11     00624        60.0
12     00627        44.7
13     00631        51.9
14     00637        49.7
15     00638        60.2
16     00641        55.7
17     00646        35.8
18     00647        54.1
19     00650        54.7
20     00652        50.6
21     00653        66.9
22     00656        53.0
23     00659        46.1
24     00660        32.8
25     00662        55.0
26     00664        52.0
27     00667        60.4
28     00669        62.9
29     00670        57.5
30     00674        46.9
...      ...         ...
33091  99786        43.1
33092  99788        33.8
33093  99789         3.7
33094  99790         0.0
33095  99791        19.2
33096  99801         5.8
33097  99820        22.3
33098  99824         9.6
33099  99825         7.7
33100  99826        11.0
33101  99827         7.7
33102  99829        16.7
33103  99830        28.1
33104  99832         4.7
33105  99833        11.4
33106  99835        10.0
33107  99836         0.0
33108  99840         5.5
33109  99841        14.2
33110  99901        10.2
33111  99903        26.7
33112  99918         9.2
33113  99919        18.7
33114  99921        15.9
33115  99922        10.8
33116  99923         4.9
33117  99925        18.8
33118  99926        12.6
33119  99927        35.1
33120  99929         9.3

[33120 rows x 2 columns]

In [8]:
census.loc[:,['HC01_VC03', 'HC01_VC171', 'HC03_VC171']]

,HC01_VC03,HC01_VC171,HC03_VC171
0,Estimate; EMPLOYMENT STATUS - Population 16 ye...,Estimate; PERCENTAGE OF FAMILIES AND PEOPLE WH...,Percent; PERCENTAGE OF FAMILIES AND PEOPLE WHO...
1,14440,(X),59.1
2,33175,(X),54.3
3,43173,(X),50.1
4,5202,(X),56.5
5,23214,(X),50.5
6,54341,(X),45.3
7,8534,(X),47.3
8,19383,(X),53.8
9,5082,(X),60.3
10,35689,(X),47.8
11,19326,(X),60.0
12,27678,(X),44.7
13,1511,(X),51.9
14,19913,(X),49.7
15,14751,(X),60.2
16,24305,(X),55.7
17,29650,(X),35.8
18,4686,(X),54.1
19,11655,(X),54.7
20,2714,(X),50.6
21,10342,(X),66.9
22,16532,(X),53.0
23,33313,(X),46.1
24,14034,(X),32.8
25,34795,(X),55.0
26,12678,(X),52.0
27,20809,(X),60.4
28,22970,(X),62.9
29,7688,(X),57.5
...,...,...,...
33091,183,(X),43.1
33092,37,(X),33.8
33093,293,(X),3.7
33094,43,(X),0.0
33095,187,(X),19.2
33096,23712,(X),5.8
33097,384,(X),22.3
33098,1780,(X),9.6
33099,66,(X),7.7
33100,467,(X),11.0
33101,2173,(X),7.7
33102,604,(X),16.7
33103,369,(X),28.1
33104,55,(X),4.7
33105,2701,(X),11.4
33106,7099,(X),10.0
33107,28,(X),0.0
33108,881,(X),5.5
33109,92,(X),14.2
33110,10772,(X),10.2
33111,30,(X),26.7
33112,120,(X),9.2
33113,404,(X),18.7
33114,1616,(X),15.9
33115,284,(X),10.8
33116,81,(X),4.9
33117,539,(X),18.8
33118,1184,(X),12.6
33119,111,(X),35.1
33120,1989,(X),9.3