In [1]:
import pandas as pd

In [2]:
census = pd.read_csv('ACS_13_5YR_DP03_with_ann.csv')

/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py:1170: DtypeWarning: Columns (1,3,4,5,7,8,9,15,16,17,19,20,23,24,27,28,31,32,33,35,36,39,40,41,43,44,47,48,49,51,52,59,60,61,63,64,67,68,71,72,75,76,79,80,83,84,85,87,88,91,92,95,96,99,100,101,103,104,107,108,111,112,115,116,119,120,121,127,128,135,136,143,144,151,152,159,160,167,168,169,175,176,177,183,184,185,187,188,191,192,195,196,197,199,200,203,204,205,207,208,209,211,212,213,215,216,219,220,223,224,225,227,228,231,232,235,236,237,239,240,243,244) have mixed types. Specify dtype option on import or set low_memory=False.
  data = self._reader.read(nrows)

In [11]:
census.GEO.id2'']head()

AttributeError: 'DataFrame' object has no attribute 'GEO'

In [8]:
census.loc[:,['HC01_VC03', 'HC01_VC171', 'HC03_VC171']]

,HC01_VC03,HC01_VC171,HC03_VC171
0,Estimate; EMPLOYMENT STATUS - Population 16 ye...,Estimate; PERCENTAGE OF FAMILIES AND PEOPLE WH...,Percent; PERCENTAGE OF FAMILIES AND PEOPLE WHO...
1,14440,(X),59.1
2,33175,(X),54.3
3,43173,(X),50.1
4,5202,(X),56.5
5,23214,(X),50.5
6,54341,(X),45.3
7,8534,(X),47.3
8,19383,(X),53.8
9,5082,(X),60.3
10,35689,(X),47.8
11,19326,(X),60.0
12,27678,(X),44.7
13,1511,(X),51.9
14,19913,(X),49.7
15,14751,(X),60.2
16,24305,(X),55.7
17,29650,(X),35.8
18,4686,(X),54.1
19,11655,(X),54.7
20,2714,(X),50.6
21,10342,(X),66.9
22,16532,(X),53.0
23,33313,(X),46.1
24,14034,(X),32.8
25,34795,(X),55.0
26,12678,(X),52.0
27,20809,(X),60.4
28,22970,(X),62.9
29,7688,(X),57.5
...,...,...,...
33091,183,(X),43.1
33092,37,(X),33.8
33093,293,(X),3.7
33094,43,(X),0.0
33095,187,(X),19.2
33096,23712,(X),5.8
33097,384,(X),22.3
33098,1780,(X),9.6
33099,66,(X),7.7
33100,467,(X),11.0
33101,2173,(X),7.7
33102,604,(X),16.7
33103,369,(X),28.1
33104,55,(X),4.7
33105,2701,(X),11.4
33106,7099,(X),10.0
33107,28,(X),0.0
33108,881,(X),5.5
33109,92,(X),14.2
33110,10772,(X),10.2
33111,30,(X),26.7
33112,120,(X),9.2
33113,404,(X),18.7
33114,1616,(X),15.9
33115,284,(X),10.8
33116,81,(X),4.9
33117,539,(X),18.8
33118,1184,(X),12.6
33119,111,(X),35.1
33120,1989,(X),9.3